version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - server-net

#  db:
#    container_name: db
#    image: mysql:latest
#    platform: linux/amd64
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_DATABASE=hackathon
#      - MYSQL_ROOT_PASSWORD=root
#      - TZ=Asia/Seoul
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - server-net

volumes:
  mysql_data:

networks:
  server-net:
    driver: bridge
