spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hackathon?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

fcm:
  value: your_fcm_value

twilio:
  account:
    sid: your_twilio_account_sid
  auth:
    token: your_twilio_auth_token
  phone:
    number: your_twilio_phone_number
